package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Category;
import ba.unsa.etf.rpr.exceptions.AppException;

import java.util.List;

public class CategoryManager {

    public void validateCategoryName(String name) throws AppException {
        if (name == null || name.length() > 45 || name.length() < 3) {
            throw new AppException("Category name must be between 3 and 45 characters.");
        }
    }

    public Category add(Category category) throws AppException {
        if (category.getId() != 0)
            throw new AppException("ID is autogenerated. Can't add category with ID.");
        validateCategoryName(category.getName());
        try {
            return DaoFactory.getCategoryDao().add(category);
        } catch (AppException e) {
            if (e.getMessage().contains("name_UNIQUE")) {
                throw new AppException("Category with the same name already exists");
            }
            throw e;
        }
    }

    public Category update(Category category) throws AppException {
        validateCategoryName(category.getName());
        return DaoFactory.getCategoryDao().update(category);
    }

    public Category getById(int id) throws AppException {
        return DaoFactory.getCategoryDao().getById(id);
    }

    public void delete(int id) throws AppException {
        DaoFactory.getCategoryDao().delete(id);
    }

    public List<Category> getAll() throws AppException {
        return DaoFactory.getCategoryDao().getAll();
    }

    public String getCategoryName(int id) throws AppException {
        return DaoFactory.getCategoryDao().getCategoryName(id);
    }

}
