package ba.unsa.etf.rpr.controllers;

import ba.unsa.etf.rpr.AppFX;
import ba.unsa.etf.rpr.business.CategoryManager;
import ba.unsa.etf.rpr.domain.Destination;
import ba.unsa.etf.rpr.exceptions.AppException;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;

import java.io.IOException;

import static javafx.scene.layout.Region.USE_COMPUTED_SIZE;

/**
 * Controller class for displaying details about a chosen destination.
 *
 * @author Almedina Pehlivan
 */
public class DetailsController {

    private final int userId;
    private final Destination destination;

    @FXML
    private Button addTripBtn;

    @FXML
    private Button cancelButton;

    @FXML
    private Label categoryLabel;

    @FXML
    private TextArea descriptionText;

    @FXML
    private Label locationLabel;

    @FXML
    private Label nameLabel;

    @FXML
    private Label ratingLabel;

    public DetailsController(int userId, Destination destination) {
        this.userId = userId;
        this.destination = destination;
    }

    /**
     * Handles the event generated by the cancel button.
     */
    @FXML
    void cancelClicked(ActionEvent event) throws IOException {
        ((Stage) cancelButton.getScene().getWindow()).close();
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/explore page.fxml"));
        Parent root = loader.load();
        ExplorePageController controller = loader.getController();
        controller.setUserId(userId);
        newStage(root, null, null);
    }

    /**
     * Initiates the process of adding the selected destination to the travel history
     */
    @FXML
    void addTripClicked(ActionEvent event) throws IOException {
        ((Stage) addTripBtn.getScene().getWindow()).close();
        newStage(null, "/fxml/trip info.fxml", new TripInfoController(userId, destination));
    }

    @FXML
    void initialize() {
        descriptionText.setEditable(false);
        try {
            populateDetails();
        } catch (AppException e) {
            new Alert(Alert.AlertType.NONE, e.getMessage(), ButtonType.OK).show();
        }
    }

    /**
     * Populates the UI components with details of the chosen destination.
     */
    private void populateDetails() throws AppException {
        CategoryManager manager = new CategoryManager();
        nameLabel.setText(destination.getName());
        ratingLabel.setText(String.valueOf(destination.getAverageRating()));
        locationLabel.setText(destination.getLocation());
        descriptionText.setText(destination.getDescription());
        categoryLabel.setText(manager.getById(destination.getCategoryId()).getName());
    }

    private void newStage(Parent root, String resource, Object controller) throws IOException {
        if (resource != null) {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(resource));
            if (controller != null)
                loader.setController(controller);
            root = loader.load();
        }
        Stage stage = new Stage();
        stage.setScene(new Scene(root, USE_COMPUTED_SIZE, USE_COMPUTED_SIZE));
        stage.setResizable(false);
        AppFX.titleAndIcon(stage);
        stage.show();
    }

}
